apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: organizations.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Organization
    plural: organizations
    singular: organization
    shortNames:
      - orgs
      - org
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.grafana.k8spin.cloud
spec:
  scope: Namespaced
  group: grafana.k8spin.cloud
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: User
    plural: users
    singular: user
    shortNames:
      - users
      - user
