apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: grafana-multi-tenant-operator
rules:
  - apiGroups: ["grafana.k8spin.cloud"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["*"]
